# fly.toml app configuration file generated for rails-fly-io-app on 2023-10-11T15:26:35+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rails-fly-io-app"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile.prod"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
